# vim:set ts=2 sw=2 sts=2 et:
---
name: 'python-poetry'
author: "@japannext"
description: Install Python, Poetry and run Poetry install command.
branding:
  icon: arrow-down
  color: green
runs:
  using: composite
  steps:
    - name: Installing Python
      uses: actions/setup-python@v2
      with: {python-version: 3.6}

    - name: Installing Poetry
      run: |
        python -m pip install 'poetry>=1.2.0a2'
        poetry --version
      shell: bash

    - name: Cache Poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: "Poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}"
        restore-keys: |
          Poetry-${{ runner.os }}-
          Poetry-

    - name: Installing dependencies
      run: poetry install
      shell: bash
