# vim:set ts=2 sw=2 sts=2 et:
---
name: Tests and lints

on:
  pull_request:
    branch: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out git repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry.yml
      - run: poetry run pylint hazelsync
  sec:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out git repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry.yml
      - run: poetry run bandit -r hazelsync
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out git repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry.yml
      - run: poetry run pytest
